name: Create Release Branch
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to create the branch from'
        type: string
        required: true
jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout Branch from tag
        run: git checkout -b release-${{ github.event.inputs.version }}  ${{ github.event.inputs.version }}
      - name: Bumb Version
        run: mvn versions:set -DnextSnapshot
      - name: Commit Pom.xml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pom.xml'
          author_name: Release Workflow
          author_email: unifiedid-admin+release@thetradedesk.com
          push: '--set-upstream origin release-${{ github.event.inputs.version }}'
          message: 'release-branch-${{ github.event.inputs.version }}'
