name: Publish Snapshot
on: workflow_dispatch

jobs:
  check_version: 
    uses: ./.github/workflows/check_version.yaml
    with:
      needs_snapshot: true
  publish:
    runs-on: ubuntu-latest
    needs: [check_version]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/download_gpg_key
        with:
          key: ${{ secrets.GPG_KEY }}
      - name: Deploy Snapshot
        run: mvn -B -Drepo.id=ossrh -Drepo.login=uidadmin -Drepo.pwd="${{ secrets.SONATYPE_REPO_PASSWORD }}" -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" clean deploy
