name: Publish Snapshot
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Version snapshot removed
        id: check_verion
        uses: ./.github/workflows/check_version
        with:
          needs_snapshot:false
      - uses: ./.github/workflows/download_gpg_key
        with:
          key: ${{ secrets.GPG_KEY }}
      - name: Deploy Snapshot
        run: mvn -B -Drepo.id=ossrh -Drepo.login=uidadmin -Drepo.pwd="${{ secrets.SONATYPE_REPO_PASSWORD }}" -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" clean deploy
