name: Release Major/Minor
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Version snapshot removed
        uses: ./.github/workflows/check_version
        with:
          needs_snapshot:false
      - uses: ./.github/workflows/download_gpg_key
        with:
          key: ${{ secrets.GPG_KEY }}
      - name: Remove Snapshot
        run: mvn -B versions:set -DremoveSnapshot
      - name: Check Version snapshot removed
        id: check_verion
        uses: ./.github/workflows/check_version
        with:
          needs_snapshot:false
      - name: Commit Pom.xml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pom.xml'
          author_name: Release Workflow
          author_email: unifiedid-admin+release@thetradedesk.com
          message: 'release-${{ steps.check_version.outputs.version }}'
          tag: '${{ steps.check_version.outputs.version }}'
      - name: Deploy Snapshot
        run: mvn -B -Drepo.id=ossrh -Drepo.login=uidadmin -Drepo.pwd="${{ secrets.SONATYPE_REPO_PASSWORD }}" -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" clean deploy
