name: Release Major/Minor
on: workflow_dispatch

jobs:
  check_version: 
    uses: ./.github/workflows/check_version.yaml
    with:
      needs_snapshot: false 
  release:
    runs-on: ubuntu-latest
    needs: [check_version]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/download_gpg_key
        with:
          key: ${{ secrets.GPG_KEY }}
      - name: Remove Snapshot
        run: mvn -B versions:set -DremoveSnapshot
      - name: Commit Pom.xml
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'pom.xml'
          author_name: Release Workflow
          author_email: unifiedid-admin+release@thetradedesk.com
          message: 'release-${{ needs.check_version.outputs.version }}'
          tag: '${{ needs.check_version.outputs.version }}'
      - name: Deploy Snapshot
        run: mvn -B -Drepo.id=ossrh -Drepo.login=uidadmin -Drepo.pwd="${{ secrets.SONATYPE_REPO_PASSWORD }}" -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" clean deploy
